# Maven/Tycho pom model adjustments, see https://github.com/eclipse-tycho/tycho/wiki/Tycho-Pomless
pom.model.property.product.id = org.eclipse.rt.osgistarterkit.product
pom.model.property.product.rootFolder = rt
pom.model.property.product.rootFolder.macosx = Rt.app

pom.model.property.eclipse.signing.skip = false
