# Maven/Tycho pom model adjustments, see https://github.com/eclipse-tycho/tycho/wiki/Tycho-Pomless
pom.model.property.repository.name = Equinox and Eclipse p2 ${releaseVersion}
pom.model.property.repository.includeAllDependencies = false
pom.model.property.repository.includeAllSources = true
pom.model.property.eclipse.signing.skip = false
