name: Check for merge commits

on:
  workflow_call:

permissions:
  contents: read

jobs:
  message-check:
    name: Block Merge Commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Block Merge Commits
        uses: Morishiri/block-merge-commits-action@a4554c78def8d874966a8d1e20e2971121443755 # v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Message
        if: ${{ failure() }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.setFailed('Please always use rebase to update your branch')
