name: Check for and apply version increments

on:
  workflow_call:
    inputs:
      botName:
        description: The name of the bot that adds the necessary version increment changes
        type: string
        required: true
      botMail:
        description: The name of the bot that adds the necessary version increment changes
        type: string
        required: true
      extra-setup-command:
        description: Optional command executed initially to perform additional setup of the build environment
        type: string
        required: false
        default: ''
      extra-maven-args:
        description: Optional additional arguments to the maven call
        type: string
        required: false
        default: ''
      working-directory:
        description: Optional additional arguments to specify the directory in which maven build is executed
        type: string
        required: false
        default: '.'
      stream-version-property:
        description: Maven property name to use for determining the stream version in commit messages
        type: string
        required: false
        default: 'releaseNumberSDK'

permissions: {} # all none

env:
  MAVEN_ARGS: >-
    --batch-mode --no-transfer-progress

jobs:
  versions-check-and-increment:
    name: Check and increment service versions
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0 # required for jgit timestamp provider to work

    - name: Set up Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: 21
        distribution: 'temurin'

      # Use a dedicated cache to prevent conflicts with the verification build cache
    - name: Cache local Maven repository
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
      with:
        path: ~/.m2/repository
        key: version-check-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          version-check-${{ runner.os }}-maven-

    - name: Set up Maven
      uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0 # v5.1
      with:
        maven-version: 3.9.16

    - name: Additional setup
      if: inputs.extra-setup-command
      run: |
        ${{ inputs.extra-setup-command }}

    - name: Check and increment versions
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +e -x
        attemptLimit=10
        attempt=0
        while ((attempt++ < ${attemptLimit})); do
          mvn verify ${{ inputs.extra-maven-args }} -DskipTests -Dcompare-version-with-baselines.skip=false \
            org.eclipse.tycho:tycho-versions-plugin:bump-versions -Dtycho.bump-versions.increment=100 \
            --update-snapshots --threads 1C --fail-at-end --show-version
          if [[ $? -eq 0 ]]; then
            echo "Attempt ${attempt} successful. Exit."
            exit 0
          fi
        done
        echo "Attempt limit of ${attemptLimit} reached. Abort!"
        exit 1

    - name: Commit version increments, if any
      run: |
        set -x
        # Only stage files relevant for version increments and don't fail if the kind of file to be staged does not exist at all.
        git add '*/META-INF/MANIFEST.MF' || true
        git add '*/feature.xml' || true
        git add '*/pom.xml' || true
        if [[ $(git diff --name-only --cached) != '' ]]; then
          # Relevant files were staged, i.e. some version were changed
          
          # Read property as stream version
          pushd ${{ inputs.working-directory }}
          mvn help:evaluate -Dexpression=${{ inputs.stream-version-property }} ${{ inputs.extra-maven-args }} --quiet '-Doutput=streamVersion-value.txt'
          streamVersion=$(<streamVersion-value.txt)
          rm -f streamVersion-value.txt
          popd
          
          git config --global user.email '${{ inputs.botMail }}'
          git config --global user.name '${{ inputs.botName }}'
          git status
          git commit -m "Version bump(s) for ${streamVersion} stream"
          
          git format-patch -1 HEAD --no-stat --output 'version_increments.patch'
          
          echo '${{ github.event.pull_request.number }}' > 'github_pull_request_number.txt'
          
          echo "::error title=Version increments are missing::Required version increments are missing and a commit to apply them is about to be pushed to your PR's branch."
          exit 1
        else
          echo 'No version increments required'
        fi

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: versions-git-patch
        path: |
          version_increments.patch
          github_pull_request_number.txt
