name: Continuous Integration
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/mavenBuild.yml
    with:
      maven-goals: clean verify -Pbuild-individual-bundles -Pjavadoc -DskipTests -Dcbi-ecj-version=99.99 -Dtycho.version=4.0.13-SNAPSHOT
      submodules: true
      extra-setup: |
        git submodule update --remote
        mvn clean install -U -pl :eclipse-sdk-prereqs,:org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99
        git clone --branch tycho-4.0.x --depth 1 https://github.com/eclipse-tycho/tycho.git 
        pushd tycho
        mvn clean install -DskipTests
        popd
