name: Publish Version Check Results

on:
  workflow_run:
    workflows: [ 'Pull-Request Checks' ]
    types: [ completed ]

jobs:
  publish-version-check-results:
    uses: ./.github/workflows/shared/publishVersionCheckResults.yml
    with:
      botGithubId: eclipse-platform-bot
    secrets:
      githubBotPAT: ${{ secrets.PLATFORM_BOT_PAT }}
